apiVersion: v1
kind: Service
metadata:
  name: llmops-service
  namespace: argocd
spec:
  selector:
    app: llmops-app
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8501
      nodePort: 30646     # <— match the live port you saw
